Metrics/LineLength:
  Enabled: false

Style/Documentation: 
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

AllCops:
  Exclude:
    - 'bin/*'
    - 'test/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'test/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'app/models/omni_user.rb'
    - 'app/controllers/omniauth_callbacks_controller.rb'
