Metrics/LineLength:
  Enabled: false

Style/Documentation: 
  Enabled: false

AllCops:
  Exclude:
    - 'bin/*'
    - 'test/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'test/**/*'
    - 'config/**/*'
    - 'db/**/*'