language: ruby
rvm:
  - 2.5.3
script:
  - gem update --system
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
  - bundle exec rubocop -a
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler -v 1.17.3