language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
  - bundle exec rubocop -a
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler -v 1.17.3
deploy:
  provider: heroku
  api_key:
    secure: "HEROKU_API_KEY"