default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: yermuv_development

test:
  <<: *default
  database: yermuv_test

production:
  <<: *default
  database: yermuv_production
  # username: yermuv
  # password: <%= ENV['YERMUV_DATABASE_PASSWORD'] %>

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   host: db
#   username: postgres
#   password:
#   pool: 5

# development:
#   <<: *default
#   database: myapp_development


# test:
#   <<: *default
#   database: myapp_test